name: Update ECR Image

on:
  push:
    branches: [ feat/jake/tf-alb-asg ]

env:
  ECR_REPOSITORY: learn-terraform

jobs:
  deploy:
    name: Deploy to ECR
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1
        
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Build and push image to Amazon ECR
      uses: docker/build-push-action@v4
      with:
        context: ./app
        push: true
        tags: ${{ steps.login-ecr.outputs.registry }}/${{ env.ECR_REPOSITORY }}:latest
        platforms: linux/amd64

    - name: Clean up
      if: always()
      run: |
        docker logout ${{ steps.login-ecr.outputs.registry }}