name: Update ECR Image

on:
  push:
    branches: [ feat/jake/tf-alb-asg ]

env:
  AWS_REGION: env.REGION
  ECR_REPOSITORY: env.ECR_URL

jobs:
  deploy:
    name: Deploy to ECR
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.REGION }}

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1
        
    - name: Build, tag, and push image to Amazon ECR
      env:
        ECR_URL: ${{ env.ECR_URL }}
      run: |
        docker build --platform linux/amd64 -t ${ECR_URL}:latest ./app
        docker push ${env.ECR_URL}:latest